--- #YAML:1.0
name:               Chess-Rep-Coverage
version:            0.0403
abstract:           Expose chess ply potential energy
author:
    - Gene Boggs <gene@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Chess::Rep:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
