# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chess-Rep-Coverage
version:      0.0401
version_from: lib/Chess/Rep/Coverage.pm
installdirs:  site
requires:
    Chess::Rep:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
