---
abstract: 'Expose chess ply potential energy'
author:
  - 'Gene Boggs <gene@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Chess-Rep-Coverage
requires:
  Chess::Rep: 0
  Imager: 0
  Imager::Color: 0
  Imager::Fill: 0
  Imager::Font: 0
  base: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Chess-Rep-Coverage
  repository: https://github.com/ology/Games/tree/master/Chess-Rep-Coverage
version: 0.09
