#!/usr/bin/perl
use strict;
use warnings;
use lib 'lib';
use Chess::Rep::Coverage;

my $g = [
    '', # rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
    'rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1',
    'rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2',
    'rnbqkbnr/pp1ppppp/8/2p5/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2',
];

my $n = 0;
for my $fen (@$g) {
    my $x = Chess::Rep::Coverage->new($fen);
    print $n++, ': ', ($n % 2 ? 'w' : 'b'), "\n", $x->dump_pos, "\n";
}
